### ISSUE TITLE
Blueline device testing

### ISSUE THREAD

**Issue by anestisb** [anestisb/android-prepare-vendor#145]
Test a clean build against a Pixel 3 device after commit https://github.com/anestisb/android-prepare-vendor/commit/45c96466ca957e8068a37332f2eecb39368175cd (various config areas & missing blobs were modified).

**Comment by anestisb** [comment]
Booting issue noticed

```
01-13 13:11:39.124  5693  5693 E System  : ******************************************
01-13 13:11:39.124  5693  5693 E System  : ************ Failure starting system services
01-13 13:11:39.124  5693  5693 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.modemservice: android.permission.MODIFY_PHONE_STATE, com.google.modemservice: android.permission.READ_PRIVILEGED_PHONE_STATE, com.google.modemservice: android.permission.DUMP, com.google.modemservice: android.permission.MANAGE_USB}
01-13 13:11:39.124  5693  5693 E System  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2005)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:89)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.systemReady(PermissionManagerService.java:2052)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21280)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:1708)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.server.SystemServer.run(SystemServer.java:437)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.server.SystemServer.main(SystemServer.java:296)
01-13 13:11:39.124  5693  5693 E System  :      at java.lang.reflect.Method.invoke(Native Method)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-13 13:11:39.124  5693  5693 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
01-13 13:11:39.124  5693  5693 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 179ms
01-13 13:11:39.124  5693  5693 E Zygote  : System zygote died with exception
01-13 13:11:39.124  5693  5693 E Zygote  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.modemservice: android.permission.MODIFY_PHONE_STATE, com.google.modemservice: android.permission.READ_PRIVILEGED_PHONE_STATE, com.google.modemservice: android.permission.DUMP, com.google.modemservice: android.permission.MANAGE_USB}
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2005)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:89)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.systemReady(PermissionManagerService.java:2052)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21280)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.server.SystemServer.startOtherServices(SystemServer.java:1708)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:437)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:296)
01-13 13:11:39.124  5693  5693 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-13 13:11:39.124  5693  5693 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
01-13 13:11:39.124  5693  5693 D AndroidRuntime: Shutting down VM
01-13 13:11:39.125  5693  5693 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
01-13 13:11:39.125  5693  5693 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.modemservice: android.permission.MODIFY_PHONE_STATE, com.google.modemservice: android.permission.READ_PRIVILEGED_PHONE_STATE, com.google.modemservice: android.permission.DUMP, com.google.modemservice: android.permission.MANAGE_USB}
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2005)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:89)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.systemReady(PermissionManagerService.java:2052)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21280)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.server.SystemServer.startOtherServices(SystemServer.java:1708)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.server.SystemServer.run(SystemServer.java:437)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.server.SystemServer.main(SystemServer.java:296)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-13 13:11:39.125  5693  5693 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
```

**Comment by anestisb** [comment]
Most likely cause is the missing "system/etc/permissions/com.google.modemservice.xml". Testing atm.

**Comment by anestisb** [comment]
Fixed in https://github.com/anestisb/android-prepare-vendor/commit/7dee0eaf3ad65bb34be68fe6fe2922af122990ea. An AOSP build against PQ1A.190105.004 was verified to properly run on a Pixel 3 device. All major functions (Camera, WiFi, GSM, bluetooth, etc.) were tested and no obvious issues found.

Marking device as supported.
